#!/usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a pavucontrol-qt state=tiled

# Autostart 
picom & 
nitrogen --restore &
bash ~/.config/polybar/launch.sh &
blueman-applet &

# Setup tall as default layout
bsp-layout set tall I &
bsp-layout set tall II &
bsp-layout set tall III &
bsp-layout set tall IV &
bsp-layout set tall V &
bsp-layout set tall VI &
bsp-layout set tall VII &
bsp-layout set tall VIII &
bsp-layout set tall IX &
bsp-layout set tall X &

# Setup Dracula Theme
bspc config presel_feedback_color "#6272a4"
bspc config normal_border_color "#44475a"

# Magenta as focus color
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"

# Cyan as focus color
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
